os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build test -project Telefocus.xcworkspace -scheme "Telefocus" iphonesimulator -destination "platform=iOS Simulator,OS=12.4,name=iPhone XR" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
notifications:
  slack: flourish-space:3oLyQURLPkVTfGEJNgvoQBZL
